import Head from "next/head";
import React from "react";
import { NavDestination } from "../../components/reservation/nav";

type Props = {};

const Destination = (props: Props) => {
  return (
    <div>
      <Head>
        <title>transfer-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavDestination />
      </main>
    </div>
  );
};

export default Destination;
